In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('datasets/lego_sets.csv')
theme = pd.read_csv('datasets/parent_themes.csv')

In [4]:
df.head()

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space

In [5]:
theme.head()

    id     name  is_licensed
0    1  Technic        False
1   22  Creator        False
2   50     Town        False
3  112   Racers        False
4  126    Space        False

In [6]:
merged_df = df.merge(theme, left_on  = 'parent_theme', right_on = 'name')

In [7]:
merged_df.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,name_y,is_licensed
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland,411,Legoland,False
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town,50,Town,False
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle,186,Castle,False
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space,126,Space,False
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space,126,Space,False

In [8]:
merged_df = merged_df.drop(columns = 'name_y')

In [9]:
licensed = merged_df[merged_df['is_licensed']==True]

In [10]:
licensed = licensed.dropna(subset = ['set_num'])

In [11]:
licensed.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
44,10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars,158,True
45,10019-1,Rebel Blockade Runner - UCS,2001,NaN,Star Wars Episode 4/5/6,Star Wars,158,True
54,10026-1,Naboo Starfighter - UCS,2002,NaN,Star Wars Episode 1,Star Wars,158,True
57,10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars,158,True
95,10075-1,Spider-Man Action Pack,2002,25.0,Spider-Man,Super Heroes,482,True

In [12]:
star_wars = licensed[licensed['parent_theme']=='Star Wars']

In [13]:
star_wars.head(5)

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
44,10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars,158,True
45,10019-1,Rebel Blockade Runner - UCS,2001,NaN,Star Wars Episode 4/5/6,Star Wars,158,True
54,10026-1,Naboo Starfighter - UCS,2002,NaN,Star Wars Episode 1,Star Wars,158,True
57,10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars,158,True
116,10123-1,Cloud City,2003,707.0,Star Wars Episode 4/5/6,Star Wars,158,True

In [14]:
star_wars.shape[0]

609

In [15]:
the_force = star_wars.shape[0]/licensed.shape[0]

In [16]:
print(the_force)
the_force = int(the_force)
print(the_force)

0.5165394402035624
0

In [18]:
sort = licensed.sort_values('year')
sort['count'] = 1

In [19]:
sort.groupby(['year', 'parent_theme']).head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
7837,7141-1,Naboo Fighter,1999,179.0,Star Wars Episode 1,Star Wars,158,True
7845,7150-1,TIE Fighter & Y-wing,1999,NaN,Star Wars Episode 4/5/6,Star Wars,158,True
7847,7151-1,Sith Infiltrator,1999,244.0,Star Wars Episode 1,Star Wars,158,True
7815,7131-1,Anakin's Podracer,1999,136.0,Star Wars Episode 1,Star Wars,158,True
7856,7161-1,Gungan Sub,1999,379.0,Star Wars Episode 1,Star Wars,158,True
...,...,...,...,...,...,...,...,...
3576,41143-1,Berry's Kitchen,2017,NaN,Disney Princess,Disney Princess,579,True
3577,41144-1,Petite's Royal Stable,2017,NaN,Disney Princess,Disney Princess,579,True
3578,41145-1,Ariel and the Magical Spell,2017,NaN,Disney Princess,Disney Princess,579,True
3579,41146-1,Cinderella's Enchanted Evening,2017,347.0,Disney Princess,Disney Princess,579,True
7725,71042-1,Silent Mary,2017,2286.0,Pirates of the Caribbean,Pirates of the Caribbean,263,True