In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('datasets/lego_sets.csv')
theme = pd.read_csv('datasets/parent_themes.csv')

In [4]:
df.head()

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space

In [5]:
theme.head()

    id     name  is_licensed
0    1  Technic        False
1   22  Creator        False
2   50     Town        False
3  112   Racers        False
4  126    Space        False

In [6]:
merged_df = df.merge(theme, left_on  = 'parent_theme', right_on = 'name')

In [7]:
merged_df.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,name_y,is_licensed
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland,411,Legoland,False
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town,50,Town,False
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle,186,Castle,False
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space,126,Space,False
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space,126,Space,False

In [8]:
merged_df = merged_df.drop(columns = 'name_y')

In [9]:
licensed = merged_df[merged_df['is_licensed']==True]

In [10]:
licensed = licensed.dropna(subset = ['set_num'])

In [11]:
licensed.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
44,10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars,158,True
45,10019-1,Rebel Blockade Runner - UCS,2001,NaN,Star Wars Episode 4/5/6,Star Wars,158,True
54,10026-1,Naboo Starfighter - UCS,2002,NaN,Star Wars Episode 1,Star Wars,158,True
57,10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars,158,True
95,10075-1,Spider-Man Action Pack,2002,25.0,Spider-Man,Super Heroes,482,True

In [12]:
star_wars = licensed[licensed['parent_theme']=='Star Wars']

In [13]:
star_wars.head(5)

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
44,10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars,158,True
45,10019-1,Rebel Blockade Runner - UCS,2001,NaN,Star Wars Episode 4/5/6,Star Wars,158,True
54,10026-1,Naboo Starfighter - UCS,2002,NaN,Star Wars Episode 1,Star Wars,158,True
57,10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars,158,True
116,10123-1,Cloud City,2003,707.0,Star Wars Episode 4/5/6,Star Wars,158,True

In [14]:
star_wars.shape[0]

609

In [15]:
the_force = star_wars.shape[0]/licensed.shape[0]

In [16]:
print(the_force)
the_force = int(the_force)
print(the_force)

0.5165394402035624
0

In [20]:
sort = licensed.sort_values('year')
sort['count'] = 1

In [24]:
sort.groupby(['year', 'parent_theme']).sum().reset_index()

,year,parent_theme,set_num,name_x,num_parts,theme_name,id,is_licensed,count
0,1999,Star Wars,7141-17150-17151-17131-17161-17130-17171-17128...,Naboo FighterTIE Fighter & Y-wingSith Infiltra...,1384.0,Star Wars Episode 1Star Wars Episode 4/5/6Star...,2054,13,13
1,2000,Disney's Mickey Mouse,4178-14167-14166-14165-14164-1,Mickey's Fishing AdventureMickey's MansionMick...,405.0,Disney's Mickey MouseDisney's Mickey MouseDisn...,1940,5,5
2,2000,Star Wars,7134-13341-1VP-87104-14151270-13343-13342-1712...,A-wing FighterStar Wars #2 - Luke/Han/Boba Min...,2580.0,Star Wars Episode 4/5/6Star Wars Episode 4/5/6...,4108,26,26
3,2001,Harry Potter,4702-14701-14704-14705-14722-14707-14708-14709...,The Final ChallengeSorting HatThe Chamber of t...,1284.0,Sorcerer's StoneSorcerer's StoneSorcerer's Sto...,2706,11,11
4,2001,Star Wars,7146-18008-1VP-28007-165028-165030-165034-1710...,TIE FighterStormtrooper™Star Wars Co-Pack of 7...,2949.0,Star Wars Episode 4/5/6Star WarsStar Wars Epis...,2212,14,14
...,...,...,...,...,...,...,...,...,...
78,2017,Disney Princess,41147-141143-141144-141145-141146-141148-1,Anna's Snow AdventureBerry's KitchenPetite's R...,347.0,Disney PrincessDisney PrincessDisney PrincessD...,3474,6,6
79,2017,Minecraft,21135-121133-121136-121137-121134-121129-12113...,The Crafting Box 2.0The Witch HutThe Ocean Mon...,5264.0,MinecraftMinecraftMinecraftMinecraftMinecraftM...,5193,9,9
80,2017,Pirates of the Caribbean,71042-1,Silent Mary,2286.0,Pirates of the Caribbean,263,1,1
81,2017,Star Wars,SW911727-1SW911722-130611-130497-130496-1SW911...,Rey's SpeederTIE Advanced foil packR2-D2First ...,7583.0,Star Wars Episode 7Star WarsStar WarsMiniStar ...,8690,55,55
82,2017,Super Heroes,5004930-15004929-1211701-141234-141233-170900-...,Accessory packBatman Battle PodBatmanBumblebee...,13123.0,BatmanBatmanBatmanSuper HeroesSuper HeroesBatm...,34704,72,72