In [7]:
import pandas as pd
import numpy as np
import os
import polars as pl
from datetime import datetime

In [8]:
df = pl.DataFrame(
    {
        "integer": [1, 2, 3],
        "date": [
            datetime(2025, 1, 1),
            datetime(2025, 1, 2),
            datetime(2025, 1, 3),
        ],
        "float": [4.0, 5.0, 6.0],
        "string": ["a", "b", "c"],
    }
)

display(df)

shape: (3, 4)
┌─────────┬─────────────────────┬───────┬────────┐
│ integer ┆ date                ┆ float ┆ string │
│ ---     ┆ ---                 ┆ ---   ┆ ---    │
│ i64     ┆ datetime[μs]        ┆ f64   ┆ str    │
╞═════════╪═════════════════════╪═══════╪════════╡
│ 1       ┆ 2025-01-01 00:00:00 ┆ 4.0   ┆ a      │
│ 2       ┆ 2025-01-02 00:00:00 ┆ 5.0   ┆ b      │
│ 3       ┆ 2025-01-03 00:00:00 ┆ 6.0   ┆ c      │
└─────────┴─────────────────────┴───────┴────────┘

In [9]:
df.write_csv("data/output.csv")
df_csv = pl.read_csv("data/output.csv")
df_csv.head()

shape: (3, 4)
┌─────────┬────────────────────────────┬───────┬────────┐
│ integer ┆ date                       ┆ float ┆ string │
│ ---     ┆ ---                        ┆ ---   ┆ ---    │
│ i64     ┆ str                        ┆ f64   ┆ str    │
╞═════════╪════════════════════════════╪═══════╪════════╡
│ 1       ┆ 2025-01-01T00:00:00.000000 ┆ 4.0   ┆ a      │
│ 2       ┆ 2025-01-02T00:00:00.000000 ┆ 5.0   ┆ b      │
│ 3       ┆ 2025-01-03T00:00:00.000000 ┆ 6.0   ┆ c      │
└─────────┴────────────────────────────┴───────┴────────┘

In [10]:
pokemon = pl.read_csv('data/pokemon_data.csv')

In [11]:
pokemon.head()

shape: (5, 12)
┌─────┬───────────────────────┬────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 80      ┆ 60    ┆ 1          ┆ false     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 120     ┆ 80    ┆ 1          ┆ false     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 50      ┆ 65    ┆ 1          ┆ false     │
└─────┴───────────────────────┴────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [12]:
pokemon.select(pl.col("*"))

shape: (800, 12)
┌─────┬───────────────────────┬─────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                  ┆ Type 1  ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                   ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                   ┆ str     ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════════╪═════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur             ┆ Grass   ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 2   ┆ Ivysaur               ┆ Grass   ┆ Poison ┆ … ┆ 80      ┆ 60    ┆ 1          ┆ false     │
│ 3   ┆ Venusaur              ┆ Grass   ┆ Poison ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass   ┆ Poison ┆ … ┆ 120     ┆ 80    ┆ 1          ┆ false     │
│ 4   ┆ Charmander            ┆ Fire    ┆ null   ┆ … ┆ 50      ┆ 65    ┆ 1          ┆ false     │
│ …   ┆ …                     ┆ …       ┆ …      ┆ … ┆ …       ┆ …     ┆ …          ┆ …         │
│ 719 ┆ Diancie               ┆ Rock    ┆ Fairy  ┆ … ┆ 150     ┆ 50    ┆ 6          ┆ true      │
│ 719 ┆ DiancieMega Diancie   ┆ Rock    ┆ Fairy  ┆ … ┆ 110     ┆ 110   ┆ 6          ┆ true      │
│ 720 ┆ HoopaHoopa Confined   ┆ Psychic ┆ Ghost  ┆ … ┆ 130     ┆ 70    ┆ 6          ┆ true      │
│ 720 ┆ HoopaHoopa Unbound    ┆ Psychic ┆ Dark   ┆ … ┆ 130     ┆ 80    ┆ 6          ┆ true      │
│ 721 ┆ Volcanion             ┆ Fire    ┆ Water  ┆ … ┆ 90      ┆ 70    ┆ 6          ┆ true      │
└─────┴───────────────────────┴─────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [13]:
pokemon.select(pl.col("Name"))

shape: (800, 1)
┌───────────────────────┐
│ Name                  │
│ ---                   │
│ str                   │
╞═══════════════════════╡
│ Bulbasaur             │
│ Ivysaur               │
│ Venusaur              │
│ VenusaurMega Venusaur │
│ Charmander            │
│ …                     │
│ Diancie               │
│ DiancieMega Diancie   │
│ HoopaHoopa Confined   │
│ HoopaHoopa Unbound    │
│ Volcanion             │
└───────────────────────┘

In [17]:
pokemon.filter(
    (pl.col("Legendary")==True) &
    (pl.col("Type 1")=="Grass")
).head()

shape: (3, 12)
┌─────┬───────────────────┬────────┬──────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name              ┆ Type 1 ┆ Type 2   ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---               ┆ ---    ┆ ---      ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str               ┆ str    ┆ str      ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════╪════════╪══════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 492 ┆ ShayminLand Forme ┆ Grass  ┆ null     ┆ … ┆ 100     ┆ 100   ┆ 4          ┆ true      │
│ 492 ┆ ShayminSky Forme  ┆ Grass  ┆ Flying   ┆ … ┆ 75      ┆ 127   ┆ 4          ┆ true      │
│ 640 ┆ Virizion          ┆ Grass  ┆ Fighting ┆ … ┆ 129     ┆ 108   ┆ 5          ┆ true      │
└─────┴───────────────────┴────────┴──────────┴───┴─────────┴───────┴────────────┴───────────┘

In [18]:
print(pokemon.sample(5))

shape: (5, 12)
┌─────┬────────────────────┬─────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name               ┆ Type 1  ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                ┆ str     ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪════════════════════╪═════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 386 ┆ DeoxysNormal Forme ┆ Psychic ┆ null   ┆ … ┆ 50      ┆ 150   ┆ 3          ┆ true      │
│ 637 ┆ Volcarona          ┆ Bug     ┆ Fire   ┆ … ┆ 105     ┆ 100   ┆ 5          ┆ false     │
│ 149 ┆ Dragonite          ┆ Dragon  ┆ Flying ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 16  ┆ Pidgey             ┆ Normal  ┆ Flying ┆ … ┆ 35      ┆ 56    ┆ 1          ┆ false     │
│ 5   ┆ Charmeleon         ┆ Fire    ┆ null   ┆ … ┆ 65      ┆ 80    ┆ 1          ┆ false     │
└─────┴────────────────────┴─────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [19]:
pokemon.columns

['#',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [21]:
pokemon.select(
    pl.col("Name").sort(),
    pl.col("HP").mean().alias("Average HP"),
    pl.col("Attack").max().alias("Max Attack"),
    pl.col("Speed")
).head(7)

shape: (7, 4)
┌─────────────────────────┬────────────┬────────────┬───────┐
│ Name                    ┆ Average HP ┆ Max Attack ┆ Speed │
│ ---                     ┆ ---        ┆ ---        ┆ ---   │
│ str                     ┆ f64        ┆ i64        ┆ i64   │
╞═════════════════════════╪════════════╪════════════╪═══════╡
│ Abomasnow               ┆ 69.25875   ┆ 190        ┆ 45    │
│ AbomasnowMega Abomasnow ┆ 69.25875   ┆ 190        ┆ 60    │
│ Abra                    ┆ 69.25875   ┆ 190        ┆ 80    │
│ Absol                   ┆ 69.25875   ┆ 190        ┆ 80    │
│ AbsolMega Absol         ┆ 69.25875   ┆ 190        ┆ 65    │
│ Accelgor                ┆ 69.25875   ┆ 190        ┆ 80    │
│ AegislashBlade Forme    ┆ 69.25875   ┆ 190        ┆ 100   │
└─────────────────────────┴────────────┴────────────┴───────┘