In [1]:
import pandas as pd
import numpy as np
import os
import polars as pl
from datetime import datetime

In [2]:
df = pl.DataFrame(
    {
        "integer": [1, 2, 3],
        "date": [
            datetime(2025, 1, 1),
            datetime(2025, 1, 2),
            datetime(2025, 1, 3),
        ],
        "float": [4.0, 5.0, 6.0],
        "string": ["a", "b", "c"],
    }
)

display(df)

shape: (3, 4)
┌─────────┬─────────────────────┬───────┬────────┐
│ integer ┆ date                ┆ float ┆ string │
│ ---     ┆ ---                 ┆ ---   ┆ ---    │
│ i64     ┆ datetime[μs]        ┆ f64   ┆ str    │
╞═════════╪═════════════════════╪═══════╪════════╡
│ 1       ┆ 2025-01-01 00:00:00 ┆ 4.0   ┆ a      │
│ 2       ┆ 2025-01-02 00:00:00 ┆ 5.0   ┆ b      │
│ 3       ┆ 2025-01-03 00:00:00 ┆ 6.0   ┆ c      │
└─────────┴─────────────────────┴───────┴────────┘

In [3]:
df.write_csv("data/output.csv")
df_csv = pl.read_csv("data/output.csv")
df_csv.head()

shape: (3, 4)
┌─────────┬────────────────────────────┬───────┬────────┐
│ integer ┆ date                       ┆ float ┆ string │
│ ---     ┆ ---                        ┆ ---   ┆ ---    │
│ i64     ┆ str                        ┆ f64   ┆ str    │
╞═════════╪════════════════════════════╪═══════╪════════╡
│ 1       ┆ 2025-01-01T00:00:00.000000 ┆ 4.0   ┆ a      │
│ 2       ┆ 2025-01-02T00:00:00.000000 ┆ 5.0   ┆ b      │
│ 3       ┆ 2025-01-03T00:00:00.000000 ┆ 6.0   ┆ c      │
└─────────┴────────────────────────────┴───────┴────────┘

In [4]:
pokemon = pl.read_csv('data/pokemon_data.csv')

In [5]:
pokemon.head()

shape: (5, 12)
┌─────┬───────────────────────┬────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 80      ┆ 60    ┆ 1          ┆ false     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 120     ┆ 80    ┆ 1          ┆ false     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 50      ┆ 65    ┆ 1          ┆ false     │
└─────┴───────────────────────┴────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [6]:
pokemon.select(pl.col("*"))

shape: (800, 12)
┌─────┬───────────────────────┬─────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                  ┆ Type 1  ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                   ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                   ┆ str     ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════════╪═════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur             ┆ Grass   ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 2   ┆ Ivysaur               ┆ Grass   ┆ Poison ┆ … ┆ 80      ┆ 60    ┆ 1          ┆ false     │
│ 3   ┆ Venusaur              ┆ Grass   ┆ Poison ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass   ┆ Poison ┆ … ┆ 120     ┆ 80    ┆ 1          ┆ false     │
│ 4   ┆ Charmander            ┆ Fire    ┆ null   ┆ … ┆ 50      ┆ 65    ┆ 1          ┆ false     │
│ …   ┆ …                     ┆ …       ┆ …      ┆ … ┆ …       ┆ …     ┆ …          ┆ …         │
│ 719 ┆ Diancie               ┆ Rock    ┆ Fairy  ┆ … ┆ 150     ┆ 50    ┆ 6          ┆ true      │
│ 719 ┆ DiancieMega Diancie   ┆ Rock    ┆ Fairy  ┆ … ┆ 110     ┆ 110   ┆ 6          ┆ true      │
│ 720 ┆ HoopaHoopa Confined   ┆ Psychic ┆ Ghost  ┆ … ┆ 130     ┆ 70    ┆ 6          ┆ true      │
│ 720 ┆ HoopaHoopa Unbound    ┆ Psychic ┆ Dark   ┆ … ┆ 130     ┆ 80    ┆ 6          ┆ true      │
│ 721 ┆ Volcanion             ┆ Fire    ┆ Water  ┆ … ┆ 90      ┆ 70    ┆ 6          ┆ true      │
└─────┴───────────────────────┴─────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [7]:
pokemon.select(pl.col("Name"))

shape: (800, 1)
┌───────────────────────┐
│ Name                  │
│ ---                   │
│ str                   │
╞═══════════════════════╡
│ Bulbasaur             │
│ Ivysaur               │
│ Venusaur              │
│ VenusaurMega Venusaur │
│ Charmander            │
│ …                     │
│ Diancie               │
│ DiancieMega Diancie   │
│ HoopaHoopa Confined   │
│ HoopaHoopa Unbound    │
│ Volcanion             │
└───────────────────────┘

In [8]:
pokemon.filter(
    (pl.col("Legendary")==True) &
    (pl.col("Type 1")=="Grass")
).head()

shape: (3, 12)
┌─────┬───────────────────┬────────┬──────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name              ┆ Type 1 ┆ Type 2   ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---               ┆ ---    ┆ ---      ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str               ┆ str    ┆ str      ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════╪════════╪══════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 492 ┆ ShayminLand Forme ┆ Grass  ┆ null     ┆ … ┆ 100     ┆ 100   ┆ 4          ┆ true      │
│ 492 ┆ ShayminSky Forme  ┆ Grass  ┆ Flying   ┆ … ┆ 75      ┆ 127   ┆ 4          ┆ true      │
│ 640 ┆ Virizion          ┆ Grass  ┆ Fighting ┆ … ┆ 129     ┆ 108   ┆ 5          ┆ true      │
└─────┴───────────────────┴────────┴──────────┴───┴─────────┴───────┴────────────┴───────────┘

In [9]:
print(pokemon.sample(5))

shape: (5, 12)
┌─────┬─────────────────────────┬────────┬─────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                    ┆ Type 1 ┆ Type 2  ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                     ┆ ---    ┆ ---     ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                     ┆ str    ┆ str     ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═════════════════════════╪════════╪═════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 40  ┆ Wigglytuff              ┆ Normal ┆ Fairy   ┆ … ┆ 50      ┆ 45    ┆ 1          ┆ false     │
│ 376 ┆ MetagrossMega Metagross ┆ Steel  ┆ Psychic ┆ … ┆ 110     ┆ 110   ┆ 3          ┆ false     │
│ 345 ┆ Lileep                  ┆ Rock   ┆ Grass   ┆ … ┆ 87      ┆ 23    ┆ 3          ┆ false     │
│ 631 ┆ Heatmor                 ┆ Fire   ┆ null    ┆ … ┆ 66      ┆ 65    ┆ 5          ┆ false     │
│ 455 ┆ Carnivine               ┆ Grass  ┆ null    ┆ … ┆ 72      ┆ 46    ┆ 4          ┆ false     │
└─────┴─────────────────────────┴────────┴─────────┴───┴─────────┴───────┴────────────┴───────────┘

In [10]:
pokemon.columns

['#',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [11]:
pokemon.select(
    pl.col("Name").sort(),
    pl.col("HP").mean().alias("Average HP"),
    pl.col("Attack").max().alias("Max Attack"),
    pl.col("Attack").min().alias("Min Attack"),
    pl.col("Speed")
).head(7)

shape: (7, 5)
┌─────────────────────────┬────────────┬────────────┬────────────┬───────┐
│ Name                    ┆ Average HP ┆ Max Attack ┆ Min Attack ┆ Speed │
│ ---                     ┆ ---        ┆ ---        ┆ ---        ┆ ---   │
│ str                     ┆ f64        ┆ i64        ┆ i64        ┆ i64   │
╞═════════════════════════╪════════════╪════════════╪════════════╪═══════╡
│ Abomasnow               ┆ 69.25875   ┆ 190        ┆ 5          ┆ 45    │
│ AbomasnowMega Abomasnow ┆ 69.25875   ┆ 190        ┆ 5          ┆ 60    │
│ Abra                    ┆ 69.25875   ┆ 190        ┆ 5          ┆ 80    │
│ Absol                   ┆ 69.25875   ┆ 190        ┆ 5          ┆ 80    │
│ AbsolMega Absol         ┆ 69.25875   ┆ 190        ┆ 5          ┆ 65    │
│ Accelgor                ┆ 69.25875   ┆ 190        ┆ 5          ┆ 80    │
│ AegislashBlade Forme    ┆ 69.25875   ┆ 190        ┆ 5          ┆ 100   │
└─────────────────────────┴────────────┴────────────┴────────────┴───────┘

In [12]:
pokemon.filter(
    pl.col("HP") > 150
)

shape: (6, 12)
┌─────┬───────────┬─────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name      ┆ Type 1  ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---       ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str       ┆ str     ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════╪═════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 113 ┆ Chansey   ┆ Normal  ┆ null   ┆ … ┆ 105     ┆ 50    ┆ 1          ┆ false     │
│ 143 ┆ Snorlax   ┆ Normal  ┆ null   ┆ … ┆ 110     ┆ 30    ┆ 1          ┆ false     │
│ 202 ┆ Wobbuffet ┆ Psychic ┆ null   ┆ … ┆ 58      ┆ 33    ┆ 2          ┆ false     │
│ 242 ┆ Blissey   ┆ Normal  ┆ null   ┆ … ┆ 135     ┆ 55    ┆ 2          ┆ false     │
│ 321 ┆ Wailord   ┆ Water   ┆ null   ┆ … ┆ 45      ┆ 60    ┆ 3          ┆ false     │
│ 594 ┆ Alomomola ┆ Water   ┆ null   ┆ … ┆ 45      ┆ 65    ┆ 5          ┆ false     │
└─────┴───────────┴─────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [13]:
gen1 = pokemon.filter(
    pl.col("Generation")==1
)

out = gen1.group_by("Type 1").agg(
    pl.col("#").count()
)

out.select(
    pl.col("Type 1"),
    pl.col("#").sort(descending = True)
)

shape: (15, 2)
┌──────────┬─────┐
│ Type 1   ┆ #   │
│ ---      ┆ --- │
│ str      ┆ u32 │
╞══════════╪═════╡
│ Poison   ┆ 31  │
│ Psychic  ┆ 24  │
│ Water    ┆ 14  │
│ Electric ┆ 14  │
│ Fire     ┆ 14  │
│ …        ┆ …   │
│ Grass    ┆ 7   │
│ Rock     ┆ 4   │
│ Normal   ┆ 3   │
│ Dragon   ┆ 2   │
│ Ice      ┆ 2   │
└──────────┴─────┘

In [14]:
out.head(2)

shape: (2, 2)
┌─────────┬─────┐
│ Type 1  ┆ #   │
│ ---     ┆ --- │
│ str     ┆ u32 │
╞═════════╪═════╡
│ Poison  ┆ 14  │
│ Psychic ┆ 11  │
└─────────┴─────┘

In [15]:
out[["Type 1", "#"]].head(3)

shape: (3, 2)
┌─────────┬─────┐
│ Type 1  ┆ #   │
│ ---     ┆ --- │
│ str     ┆ u32 │
╞═════════╪═════╡
│ Poison  ┆ 14  │
│ Psychic ┆ 11  │
│ Water   ┆ 31  │
└─────────┴─────┘

In [16]:
pokemon.filter(
    pl.col("Name").str.starts_with("B")
).head(3)

shape: (3, 12)
┌─────┬─────────────────────────┬────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                    ┆ Type 1 ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                     ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                     ┆ str    ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═════════════════════════╪════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur               ┆ Grass  ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 9   ┆ Blastoise               ┆ Water  ┆ null   ┆ … ┆ 105     ┆ 78    ┆ 1          ┆ false     │
│ 9   ┆ BlastoiseMega Blastoise ┆ Water  ┆ null   ┆ … ┆ 115     ┆ 78    ┆ 1          ┆ false     │
└─────┴─────────────────────────┴────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

# Performance Benefits of Polars

In [17]:
import pandas as pd

In [26]:
poke = pd.read_csv('data/pokemon_data.csv')

In [28]:
poke[poke['Name'].str.startswith('B')].head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False

In [29]:
poke_pl = pl.read_csv('data/pokemon_data.csv')

In [31]:
poke_pl.filter(
    pl.col('Name').str.starts_with('B')
)

shape: (43, 12)
┌─────┬─────────────────────────┬────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                    ┆ Type 1 ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                     ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                     ┆ str    ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═════════════════════════╪════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur               ┆ Grass  ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 9   ┆ Blastoise               ┆ Water  ┆ null   ┆ … ┆ 105     ┆ 78    ┆ 1          ┆ false     │
│ 9   ┆ BlastoiseMega Blastoise ┆ Water  ┆ null   ┆ … ┆ 115     ┆ 78    ┆ 1          ┆ false     │
│ 12  ┆ Butterfree              ┆ Bug    ┆ Flying ┆ … ┆ 80      ┆ 70    ┆ 1          ┆ false     │
│ 15  ┆ Beedrill                ┆ Bug    ┆ Poison ┆ … ┆ 80      ┆ 75    ┆ 1          ┆ false     │
│ …   ┆ …                       ┆ …      ┆ …      ┆ … ┆ …       ┆ …     ┆ …          ┆ …         │
│ 654 ┆ Braixen                 ┆ Fire   ┆ null   ┆ … ┆ 70      ┆ 73    ┆ 6          ┆ false     │
│ 659 ┆ Bunnelby                ┆ Normal ┆ null   ┆ … ┆ 36      ┆ 57    ┆ 6          ┆ false     │
│ 688 ┆ Binacle                 ┆ Rock   ┆ Water  ┆ … ┆ 56      ┆ 50    ┆ 6          ┆ false     │
│ 689 ┆ Barbaracle              ┆ Rock   ┆ Water  ┆ … ┆ 86      ┆ 68    ┆ 6          ┆ false     │
│ 712 ┆ Bergmite                ┆ Ice    ┆ null   ┆ … ┆ 35      ┆ 28    ┆ 6          ┆ false     │
└─────┴─────────────────────────┴────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘